const $=s=>document.querySelector(s), toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};let sb=null,user=null,projects=[],signup=false,activeProject=null,chosen=[];const CFG='deeplo2_config';
let introDone=false;function finishIntro(){if(introDone)return;introDone=true;$('#intro').classList.add('out');document.body.style.overflow='';setTimeout(()=>$('#intro')?.remove(),750)}document.body.style.overflow='hidden';$('#skipIntro').onclick=finishIntro;window.addEventListener('load',()=>setTimeout(finishIntro,2100));setTimeout(finishIntro,4200);$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$('#nav').querySelectorAll('a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function setConfig(){let c={};try{c=JSON.parse(localStorage.getItem(CFG)||'{}')}catch{}$('#sbUrl').value=c.url||'';$('#sbKey').value=c.key||'';if(c.url&&c.key&&window.supabase){try{sb=window.supabase.createClient(c.url,c.key)}catch{sb=null}}else sb=null}
function render(){ $('#count').textContent=projects.length;$('#projectList').innerHTML=projects.length?projects.map(p=>`<article class="project-card"><h3>⌘ ${esc(p.name)}</h3><small>${esc(p.project_type||p.type||'static')} · ${esc((p.created_at||'Date unavailable').toString().slice(0,10))}</small><div class="project-actions"><button class="btn" data-up="${esc(p.id)}">Upload files</button><button class="btn" data-del="${esc(p.id)}">Delete</button></div></article>`).join(''):'<div class="empty"><h3>No projects yet</h3><p>Create your first project.</p></div>';let sel=$('#uploadProject');sel.innerHTML='<option value="">Choose a project…</option>'+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(activeProject)sel.value=activeProject;$('#projectList').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{activeProject=b.dataset.up;sel.value=activeProject;$('#upload').scrollIntoView({behavior:'smooth'});toast('Choose files to upload.')});$('#projectList').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProject(b.dataset.del))}
async function load(){if(!sb){user=null;projects=[];$('#accountStatus').textContent='Not connected';$('#authOpen').classList.remove('hidden');$('#logout').classList.add('hidden');projects=[];render();return}try{const {data,error}=await sb.auth.getSession();if(error)throw error;user=data.session?.user||null;$('#accountStatus').textContent=user?'Signed in':'Configured · signed out';$('#authOpen').classList.toggle('hidden',!!user);$('#logout').classList.toggle('hidden',!user);if(user){const r=await sb.from('projects').select('id,name,project_type,created_at').order('created_at',{ascending:false});if(r.error)throw r.error;projects=r.data||[]}else projects=[];render()}catch(e){toast('Supabase error: '+e.message)}}
$('#newProject').onclick=()=>{$('#projectMessage').textContent='';$('#projectDialog').showModal()};$('#projectForm').onsubmit=async e=>{e.preventDefault();let name=$('#projectName').value.trim(),type=$('#projectType').value;if(!name)return;if(!sb||!user){$('#projectMessage').textContent='Connect Supabase and sign in before creating a project.';return}let r=await sb.from('projects').insert({owner_id:user.id,name,project_type:type}).select().single();if(r.error){$('#projectMessage').textContent=r.error.message;return}projects.unshift(r.data);activeProject=r.data.id;render();$('#projectDialog').close();$('#projectName').value='';toast('Project created')};async function listAllFiles(prefix){let out=[],offset=0;for(let page=0;page<20;page++){const r=await sb.storage.from('project-files').list(prefix,{limit:100,offset,sortBy:{column:'name',order:'asc'}});if(r.error)throw r.error;const rows=r.data||[];out.push(...rows.filter(x=>x.id));if(rows.length<100)break;offset+=100}return out}
async function removeProjectFiles(projectId){const prefix=`${user.id}/${projectId}`;const entries=await listAllFiles(prefix);const paths=entries.map(x=>`${prefix}/${x.name}`);if(paths.length){const r=await sb.storage.from('project-files').remove(paths);if(r.error)throw r.error}}
async function deleteProject(id){if(!confirm('Delete this project and its uploaded files?'))return;if(!sb||!user)return toast('Connect Supabase and sign in first.');try{await removeProjectFiles(id);let r=await sb.from('projects').delete().eq('id',id);if(r.error)throw r.error;await load();if(activeProject===id)activeProject=null;await refreshFiles();toast('Project and uploaded files deleted')}catch(e){toast('Delete failed: '+e.message)}}
$('#authOpen').onclick=()=>{$('#authMessage').textContent='';$('#authDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());function mode(s){signup=s;$('#loginTab').classList.toggle('active',!s);$('#signupTab').classList.toggle('active',s);$('#authSubmit').textContent=s?'Create account':'Login';$('#authMessage').textContent=''}$('#loginTab').onclick=()=>mode(false);$('#signupTab').onclick=()=>mode(true);$('#authForm').onsubmit=async e=>{e.preventDefault();if(!sb){$('#authMessage').textContent='First enter and save Supabase Project URL and anon/public key below.';return}$('#authSubmit').disabled=true;try{let email=$('#email').value.trim(),password=$('#password').value;let r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;$('#authMessage').textContent=signup?'Account request sent. Check email if confirmation is enabled.':'Login successful.';await load();if(!signup)setTimeout(()=>$('#authDialog').close(),700)}catch(err){$('#authMessage').textContent=err.message}finally{$('#authSubmit').disabled=false}};$('#logout').onclick=async()=>{if(sb)await sb.auth.signOut();user=null;await load();toast('Logged out')};$('#saveConfig').onclick=async()=>{let url=$('#sbUrl').value.trim().replace(/\/+$/,''),key=$('#sbKey').value.trim();if(url&&!/^https:\/\/[\w.-]+$/.test(url)){toast('Enter a valid HTTPS Supabase URL.');return}if((url&&!key)||(!url&&key)){toast('Enter both URL and anon/public key.');return}if(url)localStorage.setItem(CFG,JSON.stringify({url,key}));else localStorage.removeItem(CFG);setConfig();await load();toast(url?'Connection settings saved. Sign in to test.':'Connection settings cleared.')};
$('#files').onchange=()=>{chosen=Array.from($('#files').files||[]);$('#fileNames').textContent=chosen.length?chosen.map(f=>`${f.name} (${(f.size/1024).toFixed(1)} KB)`).join(' · '):'No files selected'};const allowed=new Set(['html','htm','css','js','json','txt','svg','png','jpg','jpeg','webp','gif','ico','zip','woff','woff2']);$('#uploadBtn').onclick=async()=>{if(!chosen.length)return toast('Select files first.');activeProject=$('#uploadProject').value;if(!activeProject)return toast('Choose a project first.');for(let f of chosen){let ext=f.name.split('.').pop().toLowerCase();if(f.size>10*1024*1024)return toast(f.name+' exceeds 10 MB.');if(!allowed.has(ext)||f.name.includes('..')||/[\\/]/.test(f.name))return toast('Unsupported or unsafe filename: '+f.name)}if(!sb||!user)return toast('Connect Supabase and sign in before uploading.');$('#uploadBtn').disabled=true;try{for(let f of chosen){let path=`${user.id}/${activeProject}/${Date.now()}-${f.name}`;let r=await sb.storage.from('project-files').upload(path,f,{upsert:false,contentType:f.type||'application/octet-stream'});if(r.error)throw r.error}toast('Uploaded to private storage. Website is not published yet.');await refreshFiles();chosen=[];$('#files').value='';$('#fileNames').textContent='No files selected'}catch(e){toast('Upload failed: '+e.message)}finally{$('#uploadBtn').disabled=false}};async function refreshFiles(){const host=$('#storedFileList'),status=$('#storedFiles'),projectId=$('#uploadProject').value;host.innerHTML='';if(!sb||!user){status.textContent='Connect Supabase and sign in to view private files.';return}if(!projectId){status.textContent='Choose a project to view uploaded files.';return}status.textContent='Loading files…';try{const prefix=`${user.id}/${projectId}`;const rows=await listAllFiles(prefix);if(!rows.length){status.textContent='No uploaded files in this project yet.';return}status.textContent=`${rows.length} file(s) · private storage`;host.innerHTML=rows.map(f=>`<div class="stored-file"><span>${esc(f.name)} <small>${f.metadata?.size?Math.max(1,Math.round(f.metadata.size/1024))+' KB':'size unknown'}</small></span><button class="btn" data-file-delete="${esc(f.name)}" type="button">Delete</button></div>`).join('');host.querySelectorAll('[data-file-delete]').forEach(btn=>btn.onclick=async()=>{if(!confirm(`Delete ${btn.dataset.fileDelete}?`))return;btn.disabled=true;try{const r=await sb.storage.from('project-files').remove([`${prefix}/${btn.dataset.fileDelete}`]);if(r.error)throw r.error;await refreshFiles();toast('File deleted')}catch(e){toast('File delete failed: '+e.message);btn.disabled=false}})}catch(e){status.textContent='Could not load files: '+e.message}}
$('#uploadProject').onchange=refreshFiles;$('#refreshFiles').onclick=refreshFiles;const originalLoad=load;load=async function(){await originalLoad();await refreshFiles()};$('#checklistBtn').onclick=()=>$('#checklist').classList.toggle('hidden');setConfig();load();if(sb)sb.auth.onAuthStateChange(()=>setTimeout(load,0));

// Static publishing: requires a configured Worker API and a signed-in Supabase session.
const API_CFG='deeplo2_api';
const apiInput=document.createElement('input');
apiInput.id='apiEndpoint';apiInput.placeholder='https://your-worker.workers.dev';apiInput.autocomplete='url';
apiInput.setAttribute('aria-label','Cloudflare Worker API URL');
const saveApi=document.createElement('button');saveApi.type='button';saveApi.className='btn';saveApi.textContent='Save API URL';
const apiHint=document.createElement('p');apiHint.className='fine';apiHint.textContent='Worker API URL is saved in this browser. Set ALLOWED_ORIGIN and R2 bucket on Cloudflare first.';
const configBox=document.querySelector('.config');
if(configBox){configBox.append(apiInput,saveApi,apiHint);try{apiInput.value=localStorage.getItem(API_CFG)||''}catch{}}
saveApi.onclick=()=>{const v=apiInput.value.trim().replace(/\/+$/,'');if(v&&!/^https:\/\/[\w.-]+$/.test(v)){toast('Enter a valid HTTPS Worker URL.');return}if(v)localStorage.setItem(API_CFG,v);else localStorage.removeItem(API_CFG);toast(v?'Worker URL saved.':'Worker URL cleared.')}
const publishFilesEl=document.querySelector('#publishFiles');
if(publishFilesEl)publishFilesEl.onchange=()=>{const fs=Array.from(publishFilesEl.files||[]);$('#publishFileNames').textContent=fs.length?`${fs.length} file(s) selected · ${(fs.reduce((n,f)=>n+f.size,0)/1024/1024).toFixed(2)} MB`:'Choose a website folder.'};
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Could not read '+file.name));r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.readAsDataURL(file)})}
const publishBtn=document.querySelector('#publishBtn');
if(publishBtn)publishBtn.onclick=async()=>{
 const status=$('#publishStatus');status.textContent='';
 const api=(localStorage.getItem(API_CFG)||'').replace(/\/+$/,'');
 const projectId=$('#uploadProject').value;
 const slug=$('#siteSlug').value.trim().toLowerCase();
 const files=Array.from(publishFilesEl.files||[]);
 if(!sb||!user)return status.textContent='Connect Supabase and sign in first.';
 if(!api)return status.textContent='Save your deployed Worker API URL in Supabase setup below first.';
 if(!projectId)return status.textContent='Choose a project in the file workspace above.';
 if(!/^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])?$/.test(slug))return status.textContent='Site name must be 3–40 lowercase letters, numbers or hyphens.';
 if(!files.length||files.length>100)return status.textContent='Choose 1–100 website files.';
 if(!files.some(f=>(f.webkitRelativePath||f.name).split('/').pop()==='index.html'))return status.textContent='Your selected folder must contain index.html.';
 const total=files.reduce((n,f)=>n+f.size,0);
 if(total>10*1024*1024||files.some(f=>f.size>2*1024*1024))return status.textContent='Site limit is 10 MB total and 2 MB per file.';
 const {data:{session}}=await sb.auth.getSession();
 if(!session?.access_token)return status.textContent='Your login session expired. Sign in again.';
 publishBtn.disabled=true;status.textContent='Preparing files…';
 try{
  const payload=[];
  for(const f of files){
   let path=f.webkitRelativePath||f.name;path=path.split('/').slice(1).join('/')||f.name;
   if(!path||path.startsWith('/')||path.split('/').some(x=>!x||x==='.'||x==='..'||x.startsWith('.')))throw new Error('Unsafe path: '+path);
   payload.push({path,contentBase64:await fileBase64(f),contentType:f.type||''});
  }
  status.textContent='Publishing website…';
  const resp=await fetch(api+'/api/publish',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({projectId,slug,files:payload})});
  const data=await resp.json().catch(()=>({error:'Invalid server response'}));
  if(!resp.ok)throw new Error(data.error||'Publish failed ('+resp.status+').');
  status.innerHTML='Published: <a target="_blank" rel="noopener noreferrer" href="'+esc(data.url)+'">'+esc(data.url)+'</a> · '+esc(data.files)+' files';
 }catch(e){status.textContent='Publish failed: '+(e?.message||'Unknown error')}
 finally{publishBtn.disabled=false}
};

// Unpublish a static site owned by the signed-in user.
const unpublishBtn=document.querySelector('#unpublishBtn');
if(unpublishBtn)unpublishBtn.onclick=async()=>{
 const status=$('#unpublishStatus');status.textContent='';
 const api=(localStorage.getItem(API_CFG)||'').replace(/\/+$/,'');
 const slug=$('#unpublishSlug').value.trim().toLowerCase();
 if(!sb||!user)return status.textContent='Connect Supabase and sign in first.';
 if(!api)return status.textContent='Save your deployed Worker API URL first.';
 if(!/^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])?$/.test(slug))return status.textContent='Enter the exact published site name.';
 const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)return status.textContent='Your login session expired. Sign in again.';
 if(!confirm('Permanently remove the published site '+slug+' and its public files?'))return;
 unpublishBtn.disabled=true;status.textContent='Removing published site…';
 try{const resp=await fetch(api+'/api/publish?slug='+encodeURIComponent(slug),{method:'DELETE',headers:{'Authorization':'Bearer '+session.access_token}});const data=await resp.json().catch(()=>({error:'Invalid server response'}));if(!resp.ok)throw new Error(data.error||'Unpublish failed.');status.textContent='Site unpublished and stored files removed.';$('#unpublishSlug').value='';}catch(e){status.textContent='Unpublish failed: '+(e?.message||'Unknown error')}finally{unpublishBtn.disabled=false}
};

// Update 3.0 domain management UI. API credentials stay in the signed-in session; provider secrets are never requested here.
const domainStatusEl=document.querySelector('#domainStatus');
const domainChallenge=document.querySelector('#dnsChallenge');
let lastDnsValue='';
async function domainApi(path,options={}){const api=(localStorage.getItem(API_CFG)||'').replace(/\/+$/,'');if(!api)throw new Error('Save your Cloudflare Worker API URL in Supabase setup first.');if(!sb||!user)throw new Error('Connect Supabase and sign in first.');const {data}=await sb.auth.getSession();const token=data?.session?.access_token;if(!token)throw new Error('Your login session expired. Sign in again.');const r=await fetch(api+path,{...options,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(d.error||'Domain request failed.');return d}
$('#addDomainBtn').onclick=async()=>{domainStatusEl.textContent='Requesting verification challenge…';domainChallenge.classList.add('hidden');try{const d=await domainApi('/api/domains/request',{method:'POST',body:JSON.stringify({slug:$('#domainSite').value.trim().toLowerCase(),domain:$('#domainName').value.trim().toLowerCase()})});lastDnsValue=d.dns.value;$('#dnsType').textContent=d.dns.type;$('#dnsHost').textContent=d.dns.name;$('#dnsValue').textContent=d.dns.value;domainChallenge.classList.remove('hidden');domainStatusEl.textContent=`${d.domain} · Pending DNS verification. Add the TXT record below.`; }catch(e){domainStatusEl.textContent=e.message}};
$('#verifyDomainBtn').onclick=async()=>{const domain=$('#domainName').value.trim().toLowerCase();if(!domain)return domainStatusEl.textContent='Enter your domain first.';domainStatusEl.textContent='Checking public DNS TXT record…';try{const d=await domainApi('/api/domains/verify?domain='+encodeURIComponent(domain));domainStatusEl.textContent=d.message+(d.verified?'':'')+(d.routingActive?'':' Custom routing / TLS still requires Cloudflare setup.');await refreshDomains();}catch(e){domainStatusEl.textContent=e.message}};
const domainListEl=document.querySelector('#domainList');
async function refreshDomains(){domainListEl.textContent='Loading domains…';try{const d=await domainApi('/api/domains/list');domainListEl.innerHTML='';if(!d.domains?.length){domainListEl.textContent='No domains added yet.';return}for(const item of d.domains){const card=document.createElement('div');card.className='domain-item';const info=document.createElement('div');const name=document.createElement('strong');name.textContent=item.domain;const detail=document.createElement('p');detail.className='muted';detail.textContent=`Site: ${item.slug} · DNS: ${item.status==='verified'?'Verified':'Pending'} · Routing: ${item.routingActive?'Active':'Not configured'} · SSL: ${item.sslStatus||'not configured'}`;info.append(name,detail);const remove=document.createElement('button');remove.className='btn danger';remove.type='button';remove.textContent='Remove';remove.onclick=async()=>{if(!confirm(`Remove ${item.domain} from DEEPLO Hosting? External DNS/Cloudflare settings are not changed.`))return;try{await domainApi('/api/domains/remove?domain='+encodeURIComponent(item.domain),{method:'DELETE'});await refreshDomains()}catch(e){domainStatusEl.textContent=e.message}};card.append(info,remove);domainListEl.append(card)}}catch(e){domainListEl.textContent=e.message}}
$('#refreshDomainsBtn').onclick=refreshDomains;
$('#copyDnsBtn').onclick=async()=>{if(!lastDnsValue)return toast('Request a domain challenge first.');try{await navigator.clipboard.writeText(lastDnsValue);toast('TXT value copied.')}catch{toast('Copy unavailable; select and copy the TXT value manually.')}};

// Update 3.3: public Worker health diagnostic; does not require login and never exposes secrets.
(()=>{const btn=document.querySelector('#checkApiBtn'),status=document.querySelector('#apiHealthStatus');if(!btn||!status)return;btn.addEventListener('click',async()=>{const api=(localStorage.getItem('deeplo2_api')||'').replace(/\/+$/,'');if(!api){status.textContent='Save the HTTPS Worker URL in Supabase setup first.';return}btn.disabled=true;status.textContent='Checking Worker…';try{const r=await fetch(api+'/api/health',{method:'GET',headers:{'Accept':'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));status.textContent='Worker reachable · '+(data.status||'health endpoint responded')+'. This does not test Supabase auth, R2 writes, DNS or TLS.'}catch(e){status.textContent='Connection failed: '+(e.message||'check URL, deployment and CORS')+'.'}finally{btn.disabled=false}})})();
